### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

In [8]:
import pandas as pd
df = pd.read_csv('./food_coded.csv', sep=',')
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4       2          1               430           NaN           315.0   
1  3.654       1          1               610           3.0           420.0   
2    3.3       1          1               720           4.0           420.0   
3    3.2       1          1               430           3.0           420.0   
4    3.5       1          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  ...  soup  sports  thai_food tortilla_calories  \
0                         9.0  ...   1.0     1.0          1            1165.0   
1                         1.0  ...   1.0     1.0          2             725.0   
2                         1.0  ...   1.0     2.0          5            1165.0   
3                         2.0  ...   1.0     2.0          5             725.0   
4                         1.0  ...   1.0     1.0          4             940.0   

   turkey_calories  type_sports veggies_day  vitamins  waffle_calories  \
0              345   car racing           5         1             1315   
1              690  Basketball            4         2              900   
2              500         none           5         1              900   
3              690          NaN           3         1             1315   
4              500     Softball           4         2              760   

                     weight  
0                       187  
1                       155  
2  I'm not answering this.   
3             Not sure, 240  
4                       190  

[5 rows x 61 columns]

In [9]:
df.head().T

0            1                         2  \
GPA                      2.4        3.654                       3.3   
Gender                     2            1                         1   
breakfast                  1            1                         1   
calories_chicken         430          610                       720   
calories_day             NaN          3.0                       4.0   
...                      ...          ...                       ...   
type_sports       car racing  Basketball                       none   
veggies_day                5            4                         5   
vitamins                   1            2                         1   
waffle_calories         1315          900                       900   
weight                   187          155  I'm not answering this.    

                              3         4  
GPA                         3.2       3.5  
Gender                        1         1  
breakfast                     1         1  
calories_chicken            430       720  
calories_day                3.0       2.0  
...                         ...       ...  
type_sports                 NaN  Softball  
veggies_day                   3         4  
vitamins                      1         2  
waffle_calories            1315       760  
weight            Not sure, 240       190  

[61 rows x 5 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   GPA                           123 non-null    object 
 1   Gender                        125 non-null    int64  
 2   breakfast                     125 non-null    int64  
 3   calories_chicken              125 non-null    int64  
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64  
 7   comfort_food                  124 non-null    object 
 8   comfort_food_reasons          124 non-null    object 
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64  
 12  cuisine                       108 non-null    float64
 13  diet_

In [12]:
df.isnull().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         21
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [13]:
df.corr()

Gender  breakfast  calories_chicken  \
Gender                        1.000000   0.130527         -0.098265   
breakfast                     0.130527   1.000000         -0.029597   
calories_chicken             -0.098265  -0.029597          1.000000   
calories_day                  0.026548  -0.112370          0.420089   
calories_scone                0.154845   0.030659          0.062835   
coffee                       -0.032178  -0.089756          0.159031   
comfort_food_reasons_coded    0.168593   0.017411         -0.068259   
cook                          0.312014  -0.005896         -0.040738   
comfort_food_reasons_coded.1  0.209109   0.018233         -0.009311   
cuisine                       0.102892  -0.050611          0.036199   
diet_current_coded            0.145155   0.111687         -0.148827   
drink                         0.203961   0.213881         -0.032772   
eating_changes_coded          0.037723   0.151237          0.040957   
eating_changes_coded1         0.006148   0.062699          0.083102   
eating_out                    0.008091  -0.018787          0.024428   
employment                    0.176573   0.036098         -0.057861   
ethnic_food                  -0.146148  -0.290289          0.090029   
exercise                     -0.128321   0.071351         -0.106730   
father_education              0.093358  -0.115924          0.008014   
fav_cuisine_coded             0.061015   0.000837         -0.065247   
fav_food                     -0.048478  -0.000459         -0.014967   
fries                        -0.075891  -0.110318          0.047425   
fruit_day                    -0.177751  -0.279577          0.112156   
grade_level                  -0.020669   0.061475          0.113915   
greek_food                   -0.083278  -0.295285          0.062942   
healthy_feeling               0.061442  -0.043184         -0.201979   
ideal_diet_coded              0.161649   0.099392         -0.118366   
income                        0.158303  -0.113346          0.144076   
indian_food                  -0.027089  -0.173496         -0.052667   
italian_food                 -0.074870  -0.095081          0.085190   
life_rewarding                0.101050  -0.130133         -0.276422   
marital_status               -0.135892   0.093300         -0.138259   
mother_education              0.022177   0.056030         -0.064962   
nutritional_check            -0.128979  -0.150635          0.193322   
on_off_campus                 0.077634  -0.019382          0.127884   
parents_cook                 -0.085307   0.054842         -0.161979   
pay_meal_out                  0.158283  -0.066398          0.067747   
persian_food                 -0.019961  -0.148975         -0.056234   
self_perception_weight       -0.221543  -0.061754          0.044320   
soup                          0.053185   0.182244         -0.000078   
sports                       -0.195833  -0.024319         -0.115366   
thai_food                    -0.119846  -0.118861          0.088459   
tortilla_calories             0.217066   0.030242          0.381808   
turkey_calories               0.152039  -0.041046          0.397642   
veggies_day                  -0.142901  -0.238174          0.152477   
vitamins                     -0.035668   0.092973         -0.196981   
waffle_calories               0.147770  -0.036627          0.347542   

                              calories_day  calories_scone    coffee  \
Gender                            0.026548    1.548454e-01 -0.032178   
breakfast                        -0.112370    3.065903e-02 -0.089756   
calories_chicken                  0.420089    6.283472e-02  0.159031   
calories_day                      1.000000    1.675793e-01  0.162121   
calories_scone                    0.167579    1.000000e+00  0.137510   
coffee                            0.162121    1.375098e-01  1.000000   
comfort_food_reasons_coded        0.018574    2.667555e-01 -0.051484   
cook                             -0.035581    1

In [15]:
df.groupby('Gender')['coffee'].mean()

Gender
1    1.763158
2    1.734694
Name: coffee, dtype: float64

### Numpy

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [1]:
import numpy as np
# Вычислите А+B, A-B
a = np.array([[1, -2, 4], [2, 0, 1]])
b = np.array([[5,2,3],[4, 6, 2]])

In [2]:
a+b

array([[6, 0, 7],
       [6, 6, 3]])

In [3]:
a-b

array([[-4, -4,  1],
       [-2, -6, -1]])

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [4]:
a = np.array([[1,2],[2,-1],[3,0]])
b = np.array([[-1, 1],[1, 2],[0, 0]])
c = a - 3*b
c

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [5]:
a = np.array([[1, -1], [2, 0], [3, 0]])
b = np.array([[1, 1], [2, 0]])
#a*b
a@b

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [6]:
a = np.array([[6, -1, 4],[2, 1, 10],[8, 0, 2]])
np.linalg.det(a)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [7]:
a = np.matrix('3 3 -1;4 1 3; 1 -2 -2')
np.linalg.inv(a)

matrix([[ 0.07407407,  0.14814815,  0.18518519],
        [ 0.2037037 , -0.09259259, -0.24074074],
        [-0.16666667,  0.16666667, -0.16666667]])